# Generated by Django 4.2.6 on 2023-11-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('stadium_name', models.CharField(max_length=30)),
                ('club_logo', models.ImageField(upload_to='club_logo/')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='club.league')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
